// Biblioteca pré-carregada de exercícios.
//
// Para acrescentar exercícios: adicione linhas aqui e suba SEED_VERSAO em
// seed.js. Na próxima abertura o app grava só os ids que ainda não existem;
// nada que você editou, ocultou ou criou é tocado.
//
// nome_en é o termo de busca do GIF no ExerciseDB.

// [id, nome, apelidos, grupo, equipamento, nome_en, tipo?, duracao_alvo?]
export const BIBLIOTECA = [
  // Peito
  ['supino-reto-barra', 'Supino reto com barra', ['supino', 'supino reto', 'bench'], 'Peito', 'Barra', 'barbell bench press'],
  ['supino-inclinado-barra', 'Supino inclinado com barra', ['supino inclinado'], 'Peito', 'Barra', 'barbell incline bench press'],
  ['supino-declinado-barra', 'Supino declinado com barra', ['supino declinado'], 'Peito', 'Barra', 'barbell decline bench press'],
  ['supino-reto-halter', 'Supino reto com halter', ['supino halter'], 'Peito', 'Halter', 'dumbbell bench press'],
  ['supino-inclinado-halter', 'Supino inclinado com halter', ['inclinado halter'], 'Peito', 'Halter', 'dumbbell incline bench press'],
  ['supino-maquina', 'Supino na máquina', ['chest press', 'supino articulado'], 'Peito', 'Máquina', 'lever chest press'],
  ['supino-smith', 'Supino no Smith', ['smith supino'], 'Peito', 'Smith', 'smith bench press'],
  ['crucifixo-halter', 'Crucifixo reto com halter', ['crucifixo', 'fly'], 'Peito', 'Halter', 'dumbbell fly'],
  ['crucifixo-maquina', 'Crucifixo na máquina', ['peck deck', 'voador', 'fly máquina'], 'Peito', 'Máquina', 'lever seated fly'],
  ['crossover', 'Crossover na polia', ['cross over', 'crucifixo polia'], 'Peito', 'Polia', 'cable cross-over variation'],
  ['flexao', 'Flexão de braço', ['flexão', 'apoio', 'push up'], 'Peito', 'Peso corporal', 'push-up'],
  ['paralelas-peito', 'Mergulho nas paralelas', ['paralela', 'dips'], 'Peito', 'Peso corporal', 'chest dip'],
  ['supino-declinado-halter', 'Supino declinado com halter', ['declinado halter'], 'Peito', 'Halter', 'dumbbell decline bench press'],
  ['supino-inclinado-maquina', 'Supino inclinado na máquina', ['supino inclinado articulado', 'inclinado máquina'], 'Peito', 'Máquina', 'lever incline chest press'],
  ['supino-inclinado-smith', 'Supino inclinado no Smith', ['smith inclinado'], 'Peito', 'Smith', 'smith incline bench press'],
  ['crucifixo-inclinado', 'Crucifixo inclinado com halter', ['crucifixo inclinado', 'fly inclinado'], 'Peito', 'Halter', 'dumbbell incline fly'],
  ['crossover-baixo', 'Crossover de baixo para cima', ['crossover baixo', 'cross invertido', 'peitoral superior polia'], 'Peito', 'Polia', 'cable low fly'],
  ['crossover-alto', 'Crossover de cima para baixo', ['crossover alto', 'cross alto'], 'Peito', 'Polia', 'cable standing fly'],
  ['pullover', 'Pullover com halter', ['pullover', 'pull over'], 'Peito', 'Halter', 'dumbbell pullover'],
  ['flexao-inclinada', 'Flexão inclinada', ['flexão no banco', 'flexão mãos elevadas'], 'Peito', 'Peso corporal', 'incline push-up'],
  ['flexao-declinada', 'Flexão declinada', ['flexão pés elevados'], 'Peito', 'Peso corporal', 'decline push-up'],
  ['supino-elastico', 'Supino com elástico', ['chest press elástico'], 'Peito', 'Elástico', 'resistance band chest press'],

  // Costas
  ['puxada-frontal', 'Puxada frontal', ['pulldown', 'puxada aberta', 'pulley frente'], 'Costas', 'Polia', 'cable lat pulldown full range of motion'],
  ['puxada-triangulo', 'Puxada com triângulo', ['puxada fechada', 'triângulo'], 'Costas', 'Polia', 'cable close grip front lat pulldown'],
  ['barra-fixa', 'Barra fixa', ['pull up', 'barra'], 'Costas', 'Peso corporal', 'pull-up'],
  ['remada-curvada', 'Remada curvada com barra', ['remada curvada', 'remada barra'], 'Costas', 'Barra', 'barbell bent over row'],
  ['remada-unilateral', 'Remada unilateral com halter', ['serrote', 'remada serrote'], 'Costas', 'Halter', 'dumbbell one arm bent-over row'],
  ['remada-baixa', 'Remada baixa na polia', ['remada sentada', 'remada baixa'], 'Costas', 'Polia', 'cable seated row'],
  ['remada-maquina', 'Remada na máquina', ['remada articulada'], 'Costas', 'Máquina', 'lever seated row'],
  ['remada-cavalinho', 'Remada cavalinho', ['t-bar', 'remada T'], 'Costas', 'Barra', 'lever t bar row'],
  ['pulldown-braco-reto', 'Pulldown com braço estendido', ['pullover polia', 'braço reto'], 'Costas', 'Polia', 'cable straight arm pulldown'],
  ['levantamento-terra', 'Levantamento terra', ['terra', 'deadlift'], 'Costas', 'Barra', 'barbell deadlift'],
  ['hiperextensao', 'Hiperextensão lombar', ['banco romano', 'lombar', 'extensão lombar'], 'Costas', 'Peso corporal', 'hyperextension'],
  ['encolhimento', 'Encolhimento com halter', ['trapézio', 'shrug'], 'Costas', 'Halter', 'dumbbell shrug'],
  ['puxada-supinada', 'Puxada supinada', ['puxada pegada invertida', 'pulldown supinado'], 'Costas', 'Polia', 'cable underhand pulldown'],
  ['puxada-nuca', 'Puxada atrás da nuca', ['puxada nuca', 'pulley nuca'], 'Costas', 'Polia', 'cable lat pulldown behind neck'],
  ['puxada-unilateral', 'Puxada unilateral na polia', ['puxada um braço'], 'Costas', 'Polia', 'cable one arm lat pulldown'],
  ['puxada-maquina', 'Puxada na máquina', ['pulldown articulado', 'puxada articulada'], 'Costas', 'Máquina', 'lever front pulldown'],
  ['barra-fixa-supinada', 'Barra fixa supinada', ['chin up', 'barra supinada'], 'Costas', 'Peso corporal', 'chin-up'],
  ['barra-fixa-assistida', 'Barra fixa assistida', ['gravitron', 'graviton', 'barra no gravitron'], 'Costas', 'Máquina', 'assisted pull-up'],
  ['remada-curvada-supinada', 'Remada curvada supinada', ['remada invertida', 'remada yates'], 'Costas', 'Barra', 'barbell reverse grip bent over row'],
  ['remada-banco-inclinado', 'Remada com halteres no banco inclinado', ['remada apoiada', 'remada banco 45', 'remada peito apoiado'], 'Costas', 'Halter', 'dumbbell incline row'],
  ['remada-baixa-aberta', 'Remada baixa aberta', ['remada baixa pegada aberta', 'remada barra longa'], 'Costas', 'Polia', 'cable seated wide-grip row'],
  ['remada-unilateral-polia', 'Remada unilateral na polia', ['remada um braço polia'], 'Costas', 'Polia', 'cable one arm bent over row'],
  ['remada-pendlay', 'Remada Pendlay', ['pendlay'], 'Costas', 'Barra', 'barbell pendlay row'],
  ['remada-smith', 'Remada no Smith', ['remada curvada smith'], 'Costas', 'Smith', 'smith bent over row'],
  ['remada-invertida', 'Remada invertida', ['remada australiana', 'remada no smith deitado'], 'Costas', 'Peso corporal', 'inverted row'],
  ['remada-trx', 'Remada no TRX', ['remada suspensa', 'trx remada'], 'Costas', 'TRX', 'suspension row'],
  ['terra-hexagonal', 'Levantamento terra com barra hexagonal', ['trap bar', 'hex bar', 'terra hexagonal'], 'Costas', 'Barra', 'trap bar deadlift'],
  ['encolhimento-barra', 'Encolhimento com barra', ['trapézio barra', 'shrug barra'], 'Costas', 'Barra', 'barbell shrug'],
  ['encolhimento-smith', 'Encolhimento no Smith', ['trapézio smith'], 'Costas', 'Smith', 'smith shrug'],
  ['superman', 'Superman', ['extensão lombar no chão', 'super-homem'], 'Costas', 'Peso corporal', 'superman'],

  // Ombros
  ['desenvolvimento-halter', 'Desenvolvimento com halter', ['desenvolvimento', 'press ombro'], 'Ombros', 'Halter', 'dumbbell seated shoulder press'],
  ['desenvolvimento-barra', 'Desenvolvimento militar com barra', ['militar', 'press militar'], 'Ombros', 'Barra', 'barbell seated overhead press'],
  ['desenvolvimento-maquina', 'Desenvolvimento na máquina', ['desenvolvimento articulado'], 'Ombros', 'Máquina', 'lever shoulder press'],
  ['elevacao-lateral', 'Elevação lateral com halter', ['lateral', 'elevação lateral'], 'Ombros', 'Halter', 'dumbbell lateral raise'],
  ['elevacao-lateral-polia', 'Elevação lateral na polia', ['lateral polia'], 'Ombros', 'Polia', 'cable lateral raise'],
  ['elevacao-frontal', 'Elevação frontal com halter', ['frontal'], 'Ombros', 'Halter', 'dumbbell front raise'],
  ['crucifixo-inverso', 'Crucifixo inverso', ['voador inverso', 'posterior de ombro', 'reverse fly'], 'Ombros', 'Máquina', 'lever seated reverse fly'],
  ['face-pull', 'Face pull', ['puxada para o rosto'], 'Ombros', 'Polia', 'cable rear delt row (with rope)'],
  ['remada-alta', 'Remada alta', ['upright row'], 'Ombros', 'Barra', 'barbell upright row'],
  ['desenvolvimento-arnold', 'Desenvolvimento Arnold', ['arnold', 'arnold press'], 'Ombros', 'Halter', 'dumbbell arnold press'],
  ['desenvolvimento-smith', 'Desenvolvimento no Smith', ['desenvolvimento smith'], 'Ombros', 'Smith', 'smith seated shoulder press'],
  ['desenvolvimento-em-pe', 'Desenvolvimento em pé com barra', ['overhead press', 'desenvolvimento em pé'], 'Ombros', 'Barra', 'barbell standing military press'],
  ['elevacao-lateral-maquina', 'Elevação lateral na máquina', ['lateral máquina'], 'Ombros', 'Máquina', 'lever lateral raise'],
  ['elevacao-frontal-anilha', 'Elevação frontal com anilha', ['frontal anilha', 'volante'], 'Ombros', 'Anilha', 'weighted front raise'],
  ['elevacao-frontal-polia', 'Elevação frontal na polia', ['frontal polia'], 'Ombros', 'Polia', 'cable front raise'],
  ['crucifixo-inverso-halter', 'Crucifixo inverso com halter', ['posterior de ombro halter', 'crucifixo invertido', 'voador inverso halter'], 'Ombros', 'Halter', 'dumbbell rear fly'],
  ['crucifixo-inverso-polia', 'Crucifixo inverso na polia', ['cross inverso', 'posterior na polia'], 'Ombros', 'Polia', 'cable rear delt fly'],
  ['remada-alta-polia', 'Remada alta na polia', ['upright row polia'], 'Ombros', 'Polia', 'cable upright row'],
  ['elevacao-y', 'Elevação em Y', ['Y raise', 'elevação Y'], 'Ombros', 'Halter', 'dumbbell incline y-raise'],
  ['rotacao-externa', 'Rotação externa na polia', ['manguito rotador', 'rotador externo'], 'Ombros', 'Polia', 'cable external rotation'],
  ['desenvolvimento-elastico', 'Desenvolvimento com elástico', ['press ombro elástico'], 'Ombros', 'Elástico', 'resistance band shoulder press'],

  // Bíceps
  ['rosca-direta', 'Rosca direta com barra', ['rosca direta', 'rosca barra'], 'Bíceps', 'Barra', 'barbell curl'],
  ['rosca-barra-w', 'Rosca com barra W', ['rosca W'], 'Bíceps', 'Barra W', 'ez barbell curl'],
  ['rosca-alternada', 'Rosca alternada com halter', ['alternada', 'rosca halter'], 'Bíceps', 'Halter', 'dumbbell alternate biceps curl'],
  ['rosca-martelo', 'Rosca martelo', ['martelo', 'hammer'], 'Bíceps', 'Halter', 'dumbbell hammer curl'],
  ['rosca-scott', 'Rosca Scott', ['scott', 'banco scott'], 'Bíceps', 'Barra W', 'ez barbell preacher curl'],
  ['rosca-concentrada', 'Rosca concentrada', ['concentrada'], 'Bíceps', 'Halter', 'dumbbell concentration curl'],
  ['rosca-polia', 'Rosca na polia', ['rosca cabo'], 'Bíceps', 'Polia', 'cable curl'],
  ['rosca-inclinada', 'Rosca inclinada com halter', ['rosca 45', 'rosca banco inclinado'], 'Bíceps', 'Halter', 'dumbbell incline curl'],
  ['rosca-direta-halter', 'Rosca direta com halteres', ['rosca simultânea', 'rosca halteres'], 'Bíceps', 'Halter', 'dumbbell biceps curl'],
  ['rosca-martelo-corda', 'Rosca martelo na corda', ['martelo corda', 'martelo polia'], 'Bíceps', 'Polia', 'cable hammer curl (with rope)'],
  ['rosca-scott-maquina', 'Rosca Scott na máquina', ['scott máquina', 'scott articulado'], 'Bíceps', 'Máquina', 'lever preacher curl'],
  ['rosca-scott-halter', 'Rosca Scott unilateral com halter', ['scott halter', 'scott unilateral'], 'Bíceps', 'Halter', 'dumbbell preacher curl'],
  ['rosca-spider', 'Rosca spider', ['rosca aranha', 'spider curl'], 'Bíceps', 'Barra W', 'ez bar spider curl'],
  ['rosca-21', 'Rosca 21', ['21', 'rosca vinte e um'], 'Bíceps', 'Barra', 'barbell curl'],
  ['rosca-bayesiana', 'Rosca bayesiana na polia', ['bayesian curl', 'rosca polia de costas'], 'Bíceps', 'Polia', 'cable curl behind back'],
  ['rosca-maquina', 'Rosca bíceps na máquina', ['rosca articulada'], 'Bíceps', 'Máquina', 'lever bicep curl'],
  ['rosca-polia-alta', 'Rosca na polia alta', ['bíceps no crossover', 'rosca duplo polia alta'], 'Bíceps', 'Polia', 'cable overhead curl'],
  ['rosca-zottman', 'Rosca Zottman', ['zottman'], 'Bíceps', 'Halter', 'dumbbell zottman curl'],
  ['rosca-elastico', 'Rosca com elástico', ['bíceps elástico'], 'Bíceps', 'Elástico', 'resistance band biceps curl'],

  // Tríceps
  ['triceps-pulley', 'Tríceps pulley com barra', ['pulley', 'tríceps barra'], 'Tríceps', 'Polia', 'cable pushdown'],
  ['triceps-corda', 'Tríceps na corda', ['corda', 'tríceps corda'], 'Tríceps', 'Polia', 'cable pushdown (with rope attachment)'],
  ['triceps-testa', 'Tríceps testa', ['testa', 'skull crusher'], 'Tríceps', 'Barra W', 'ez barbell lying triceps extension'],
  ['triceps-frances', 'Tríceps francês', ['francês', 'tríceps nuca'], 'Tríceps', 'Halter', 'dumbbell seated triceps extension'],
  ['triceps-coice', 'Tríceps coice', ['coice', 'kickback'], 'Tríceps', 'Halter', 'dumbbell kickback'],
  ['mergulho-banco', 'Mergulho no banco', ['tríceps banco', 'bench dip'], 'Tríceps', 'Peso corporal', 'bench dip (knees bent)'],
  ['supino-fechado', 'Supino fechado', ['supino pegada fechada'], 'Tríceps', 'Barra', 'barbell close-grip bench press'],
  ['triceps-pulley-inverso', 'Tríceps pulley pegada invertida', ['pulley supinado', 'tríceps inverso'], 'Tríceps', 'Polia', 'cable reverse grip pushdown'],
  ['triceps-unilateral-polia', 'Tríceps unilateral na polia', ['tríceps um braço'], 'Tríceps', 'Polia', 'cable one arm tricep pushdown'],
  ['triceps-frances-polia', 'Tríceps francês na polia', ['francês corda', 'tríceps overhead corda'], 'Tríceps', 'Polia', 'cable overhead triceps extension (rope attachment)'],
  ['triceps-frances-unilateral', 'Tríceps francês unilateral', ['francês um braço'], 'Tríceps', 'Halter', 'dumbbell one arm seated triceps extension'],
  ['triceps-testa-halter', 'Tríceps testa com halteres', ['testa halter'], 'Tríceps', 'Halter', 'dumbbell lying triceps extension'],
  ['triceps-testa-polia', 'Tríceps testa na polia', ['testa polia'], 'Tríceps', 'Polia', 'cable lying triceps extension'],
  ['triceps-maquina', 'Tríceps na máquina', ['tríceps articulado', 'mergulho na máquina'], 'Tríceps', 'Máquina', 'lever triceps dip'],
  ['paralelas-triceps', 'Mergulho nas paralelas (tríceps)', ['paralela tríceps', 'dips tríceps'], 'Tríceps', 'Peso corporal', 'triceps dip'],
  ['triceps-coice-polia', 'Tríceps coice na polia', ['kickback polia', 'coice polia tríceps'], 'Tríceps', 'Polia', 'cable triceps kickback'],
  ['flexao-diamante', 'Flexão diamante', ['flexão fechada', 'flexão tríceps'], 'Tríceps', 'Peso corporal', 'diamond push-up'],
  ['triceps-elastico', 'Tríceps com elástico', ['pushdown elástico'], 'Tríceps', 'Elástico', 'resistance band pushdown'],

  // Antebraço
  ['rosca-punho', 'Rosca de punho', ['punho', 'flexão de punho'], 'Antebraço', 'Barra', 'barbell wrist curl'],
  ['rosca-inversa', 'Rosca inversa', ['pegada pronada'], 'Antebraço', 'Barra', 'barbell reverse curl'],
  ['rosca-punho-inversa', 'Rosca de punho inversa', ['extensão de punho', 'punho invertido'], 'Antebraço', 'Barra', 'barbell reverse wrist curl'],
  ['rolo-punho', 'Rolo de punho', ['wrist roller', 'enrolar corda'], 'Antebraço', 'Anilha', 'wrist roller'],
  ['suspensao-barra', 'Suspensão na barra', ['dead hang', 'pendurar na barra', 'pegada isométrica'], 'Antebraço', 'Peso corporal', 'dead hang', 'tempo', 30],

  // Quadríceps
  ['agachamento-livre', 'Agachamento livre', ['agachamento', 'squat'], 'Quadríceps', 'Barra', 'barbell full squat'],
  ['agachamento-smith', 'Agachamento no Smith', ['smith agachamento'], 'Quadríceps', 'Smith', 'smith squat'],
  ['agachamento-goblet', 'Agachamento goblet', ['goblet'], 'Quadríceps', 'Halter', 'dumbbell goblet squat'],
  ['leg-press', 'Leg press 45°', ['leg', 'leg 45', 'legpress'], 'Quadríceps', 'Máquina', 'sled 45° leg press'],
  ['hack', 'Agachamento hack', ['hack machine', 'hack'], 'Quadríceps', 'Máquina', 'sled hack squat'],
  ['cadeira-extensora', 'Cadeira extensora', ['extensora'], 'Quadríceps', 'Máquina', 'lever leg extension'],
  ['bulgaro', 'Agachamento búlgaro', ['búlgaro', 'split squat'], 'Quadríceps', 'Halter', 'dumbbell single leg split squat'],
  ['afundo', 'Afundo', ['passada', 'avanço', 'lunge'], 'Quadríceps', 'Halter', 'dumbbell lunge'],
  ['cadeira-isometrica', 'Cadeira isométrica', ['wall sit', 'isometria parede'], 'Quadríceps', 'Peso corporal', 'wall sit', 'tempo', 45],
  ['agachamento-frontal', 'Agachamento frontal', ['front squat', 'agachamento pela frente'], 'Quadríceps', 'Barra', 'barbell front squat'],
  ['agachamento-sem-peso', 'Agachamento livre sem peso', ['air squat', 'agachamento peso corporal'], 'Quadríceps', 'Peso corporal', 'bodyweight squat'],
  ['agachamento-pendulo', 'Agachamento pêndulo', ['pêndulo', 'pendulum squat'], 'Quadríceps', 'Máquina', 'lever pendulum squat'],
  ['agachamento-sissy', 'Agachamento sissy', ['sissy', 'sissy squat'], 'Quadríceps', 'Peso corporal', 'sissy squat'],
  ['agachamento-salto', 'Agachamento com salto', ['jump squat', 'agachamento pliométrico'], 'Quadríceps', 'Peso corporal', 'jump squat'],
  ['bulgaro-smith', 'Agachamento búlgaro no Smith', ['búlgaro smith'], 'Quadríceps', 'Smith', 'smith split squat'],
  ['leg-press-horizontal', 'Leg press horizontal', ['leg sentado', 'leg horizontal'], 'Quadríceps', 'Máquina', 'lever seated leg press'],
  ['leg-press-unilateral', 'Leg press unilateral', ['leg uma perna'], 'Quadríceps', 'Máquina', 'sled 45 degrees one leg press'],
  ['extensora-unilateral', 'Cadeira extensora unilateral', ['extensora uma perna'], 'Quadríceps', 'Máquina', 'lever single leg extension'],
  ['afundo-smith', 'Afundo no Smith', ['passada smith', 'avanço smith'], 'Quadríceps', 'Smith', 'smith lunge'],
  ['afundo-reverso', 'Afundo reverso', ['recuo', 'passada para trás'], 'Quadríceps', 'Halter', 'dumbbell rear lunge'],
  ['passada-andando', 'Passada andando', ['avanço caminhando', 'walking lunge', 'passada caminhando'], 'Quadríceps', 'Halter', 'dumbbell walking lunge'],
  ['subida-banco', 'Subida no banco', ['step up', 'subida no step', 'subida no caixote'], 'Quadríceps', 'Halter', 'dumbbell step-up'],

  // Posterior
  ['mesa-flexora', 'Mesa flexora', ['flexora deitada', 'flexora'], 'Posterior', 'Máquina', 'lever lying leg curl'],
  ['cadeira-flexora', 'Cadeira flexora', ['flexora sentada'], 'Posterior', 'Máquina', 'lever seated leg curl'],
  ['stiff', 'Stiff', ['stiff barra'], 'Posterior', 'Barra', 'barbell straight leg deadlift'],
  ['terra-romeno', 'Levantamento terra romeno', ['romeno', 'RDL'], 'Posterior', 'Barra', 'barbell romanian deadlift'],
  ['flexora-em-pe', 'Flexora em pé', ['flexora unilateral'], 'Posterior', 'Máquina', 'lever standing leg curl'],
  ['stiff-halter', 'Stiff com halteres', ['stiff halter'], 'Posterior', 'Halter', 'dumbbell stiff leg deadlift'],
  ['terra-romeno-halter', 'Terra romeno com halteres', ['RDL halter', 'romeno halter'], 'Posterior', 'Halter', 'dumbbell romanian deadlift'],
  ['stiff-unilateral', 'Stiff unilateral', ['stiff uma perna', 'terra unilateral'], 'Posterior', 'Halter', 'dumbbell single leg deadlift'],
  ['flexao-nordica', 'Flexão nórdica', ['nórdico', 'nordic curl'], 'Posterior', 'Peso corporal', 'nordic hamstring curl'],
  ['good-morning', 'Good morning', ['bom dia'], 'Posterior', 'Barra', 'barbell good morning'],

  // Glúteos
  ['elevacao-pelvica', 'Elevação pélvica', ['hip thrust', 'pélvica'], 'Glúteos', 'Barra', 'barbell glute bridge'],
  ['gluteo-polia', 'Glúteo na polia', ['coice polia', 'kickback glúteo'], 'Glúteos', 'Polia', 'cable kickback'],
  ['cadeira-abdutora', 'Cadeira abdutora', ['abdutora', 'abdução'], 'Glúteos', 'Máquina', 'lever seated hip abduction'],
  ['agachamento-sumo', 'Agachamento sumô', ['sumô'], 'Glúteos', 'Halter', 'sumo squat'],
  ['elevacao-pelvica-maquina', 'Elevação pélvica na máquina', ['hip thrust máquina', 'pélvica máquina'], 'Glúteos', 'Máquina', 'lever hip thrust'],
  ['elevacao-pelvica-smith', 'Elevação pélvica no Smith', ['hip thrust smith', 'pélvica smith'], 'Glúteos', 'Smith', 'smith hip thrust'],
  ['ponte-gluteo', 'Ponte de glúteo', ['ponte', 'glute bridge'], 'Glúteos', 'Peso corporal', 'low glute bridge on floor'],
  ['gluteo-quatro-apoios', 'Glúteo quatro apoios', ['coice no chão', 'donkey kick', 'quatro apoios'], 'Glúteos', 'Peso corporal', 'donkey kick'],
  ['gluteo-maquina', 'Glúteo na máquina', ['coice máquina', 'glúteo articulado'], 'Glúteos', 'Máquina', 'lever kickback'],
  ['abducao-polia', 'Abdução de quadril na polia', ['abdução polia', 'abdução em pé'], 'Glúteos', 'Polia', 'cable hip abduction'],
  ['abducao-elastico', 'Caminhada lateral com elástico', ['monster walk', 'abdução elástico', 'caminhada lateral'], 'Glúteos', 'Elástico', 'resistance band lateral walk'],
  ['pull-through', 'Pull through na polia', ['puxada entre as pernas'], 'Glúteos', 'Polia', 'cable pull through'],
  ['terra-sumo', 'Levantamento terra sumô', ['terra sumô'], 'Glúteos', 'Barra', 'barbell sumo deadlift'],

  // Adutores
  ['cadeira-adutora', 'Cadeira adutora', ['adutora', 'adução'], 'Adutores', 'Máquina', 'lever seated hip adduction'],
  ['aducao-polia', 'Adução de quadril na polia', ['adução polia', 'adução em pé'], 'Adutores', 'Polia', 'cable hip adduction'],
  ['prancha-copenhagen', 'Prancha Copenhagen', ['copenhagen', 'prancha adutor'], 'Adutores', 'Peso corporal', 'copenhagen plank', 'tempo', 20],

  // Panturrilha
  ['panturrilha-em-pe', 'Panturrilha em pé', ['gêmeos', 'panturrilha'], 'Panturrilha', 'Máquina', 'lever standing calf raise'],
  ['panturrilha-sentado', 'Panturrilha sentado', ['sóleo', 'panturrilha banco'], 'Panturrilha', 'Máquina', 'lever seated calf raise'],
  ['panturrilha-leg', 'Panturrilha no leg press', ['panturrilha leg'], 'Panturrilha', 'Máquina', 'sled calf press on leg press'],
  ['panturrilha-smith', 'Panturrilha no Smith', ['gêmeos smith'], 'Panturrilha', 'Smith', 'smith calf raise'],
  ['panturrilha-unilateral', 'Panturrilha unilateral com halter', ['panturrilha no degrau', 'panturrilha uma perna'], 'Panturrilha', 'Halter', 'dumbbell single leg calf raise'],
  ['panturrilha-burrinho', 'Panturrilha burrinho', ['donkey calf', 'burrinho'], 'Panturrilha', 'Máquina', 'donkey calf raise'],
  ['elevacao-tibial', 'Elevação de tibial', ['tibial anterior', 'dorsiflexão'], 'Panturrilha', 'Peso corporal', 'tibialis raise'],

  // Abdômen
  ['abdominal-crunch', 'Abdominal crunch', ['abdominal', 'abdominal supra', 'crunch'], 'Abdômen', 'Peso corporal', 'crunch floor'],
  ['abdominal-infra', 'Elevação de pernas', ['abdominal infra', 'infra'], 'Abdômen', 'Peso corporal', 'lying leg raise flat bench'],
  ['abdominal-polia', 'Abdominal na polia', ['abdominal ajoelhado', 'cable crunch'], 'Abdômen', 'Polia', 'cable kneeling crunch'],
  ['abdominal-maquina', 'Abdominal na máquina', ['abdominal aparelho'], 'Abdômen', 'Máquina', 'lever seated crunch'],
  ['roda-abdominal', 'Roda abdominal', ['rodinha', 'ab wheel'], 'Abdômen', 'Peso corporal', 'wheel rollout'],
  ['russian-twist', 'Russian twist', ['giro russo', 'rotação'], 'Abdômen', 'Peso corporal', 'russian twist'],
  ['prancha', 'Prancha', ['prancha frontal', 'plank'], 'Abdômen', 'Peso corporal', 'front plank', 'tempo', 45],
  ['prancha-lateral', 'Prancha lateral', ['side plank'], 'Abdômen', 'Peso corporal', 'side plank', 'tempo', 30],
  ['abdominal-bicicleta', 'Abdominal bicicleta', ['bicycle crunch', 'bicicletinha'], 'Abdômen', 'Peso corporal', 'bicycle crunch'],
  ['abdominal-obliquo', 'Abdominal oblíquo', ['oblíquo', 'abdominal lateral'], 'Abdômen', 'Peso corporal', 'oblique crunches floor'],
  ['abdominal-remador', 'Abdominal remador', ['canivete', 'V-up'], 'Abdômen', 'Peso corporal', 'v-up'],
  ['elevacao-pernas-barra', 'Elevação de pernas na barra', ['infra na barra', 'abdominal suspenso'], 'Abdômen', 'Peso corporal', 'hanging leg raise'],
  ['elevacao-joelhos-paralela', 'Elevação de joelhos na paralela', ['infra na paralela', 'cadeira do capitão'], 'Abdômen', 'Peso corporal', 'captains chair straight leg raise'],
  ['abdominal-declinado', 'Abdominal declinado', ['abdominal banco declinado'], 'Abdômen', 'Peso corporal', 'decline crunch'],
  ['abdominal-bola', 'Abdominal na bola suíça', ['abdominal fitball', 'bola suíça'], 'Abdômen', 'Bola', 'stability ball crunch'],
  ['dead-bug', 'Dead bug', ['inseto morto'], 'Abdômen', 'Peso corporal', 'dead bug'],
  ['hollow-hold', 'Hollow hold', ['canoa', 'barquinho'], 'Abdômen', 'Peso corporal', 'hollow hold', 'tempo', 30],
  ['lenhador', 'Lenhador na polia', ['woodchopper', 'rotação na polia'], 'Abdômen', 'Polia', 'cable standing woodchop'],
  ['pallof', 'Pallof press', ['antirrotação', 'pallof'], 'Abdômen', 'Polia', 'cable pallof press'],
  ['prancha-trx', 'Prancha no TRX', ['prancha suspensa'], 'Abdômen', 'TRX', 'suspension plank', 'tempo', 30],

  // Cardio
  ['esteira', 'Esteira', ['corrida', 'caminhada'], 'Cardio', 'Aparelho aeróbico', 'walking on incline treadmill', 'tempo', 600],
  ['bicicleta', 'Bicicleta ergométrica', ['bike', 'bicicleta'], 'Cardio', 'Aparelho aeróbico', 'stationary bike walk', 'tempo', 600],
  ['eliptico', 'Elíptico', ['transport', 'elíptico'], 'Cardio', 'Aparelho aeróbico', 'elliptical machine walk', 'tempo', 600],
  ['escada', 'Escada', ['simulador de escada', 'stair'], 'Cardio', 'Aparelho aeróbico', 'walking on stepmill', 'tempo', 600],
  ['pular-corda', 'Pular corda', ['corda'], 'Cardio', 'Peso corporal', 'jump rope', 'tempo', 120],
  ['remo-ergometro', 'Remo ergômetro', ['remo', 'remada aeróbica'], 'Cardio', 'Aparelho aeróbico', 'rowing machine', 'tempo', 600],
  ['air-bike', 'Air bike', ['assault bike', 'bike de ar'], 'Cardio', 'Aparelho aeróbico', 'air bike', 'tempo', 300],
  ['bicicleta-horizontal', 'Bicicleta horizontal', ['bike reclinada', 'bike horizontal'], 'Cardio', 'Aparelho aeróbico', 'recumbent bike', 'tempo', 900],
  ['spinning', 'Spinning', ['bike indoor', 'ciclismo indoor'], 'Cardio', 'Aparelho aeróbico', 'stationary bike run', 'tempo', 1800],
  ['esteira-corrida', 'Corrida na esteira', ['correr', 'tiros na esteira'], 'Cardio', 'Aparelho aeróbico', 'run on treadmill', 'tempo', 1200],
  ['polichinelo', 'Polichinelo', ['jumping jack'], 'Cardio', 'Peso corporal', 'jumping jack', 'tempo', 60],

  // Funcional
  ['kettlebell-swing', 'Kettlebell swing', ['swing', 'balanço kettlebell'], 'Funcional', 'Kettlebell', 'kettlebell swing'],
  ['levantamento-turco', 'Levantamento turco', ['turkish get up', 'get up'], 'Funcional', 'Kettlebell', 'kettlebell turkish get up (squat style)'],
  ['thruster', 'Thruster', ['agachamento com desenvolvimento'], 'Funcional', 'Halter', 'dumbbell thruster'],
  ['power-clean', 'Power clean', ['clean', 'arremesso'], 'Funcional', 'Barra', 'barbell power clean'],
  ['burpee', 'Burpee', ['burpe'], 'Funcional', 'Peso corporal', 'burpee'],
  ['salto-caixote', 'Salto no caixote', ['box jump', 'caixote'], 'Funcional', 'Peso corporal', 'box jump'],
  ['wall-ball', 'Wall ball', ['arremesso na parede'], 'Funcional', 'Bola', 'medicine ball wall ball'],
  ['slam-ball', 'Slam ball', ['arremesso de bola no chão', 'bola ao chão'], 'Funcional', 'Bola', 'medicine ball slam'],
  ['escalador', 'Escalador', ['mountain climber', 'alpinista'], 'Funcional', 'Peso corporal', 'mountain climber', 'tempo', 30],
  ['corda-naval', 'Corda naval', ['battle rope', 'cordas'], 'Funcional', 'Outro', 'battling ropes', 'tempo', 30],
  ['caminhada-fazendeiro', 'Caminhada do fazendeiro', ['farmer walk', 'farmer'], 'Funcional', 'Halter', 'farmers walk', 'tempo', 45],
  ['empurrar-treno', 'Empurrar trenó', ['sled push', 'trenó'], 'Funcional', 'Outro', 'sled push', 'tempo', 30],

  // Alongamento
  ['alongamento-posterior', 'Alongamento de posterior de coxa', ['alongar posterior'], 'Alongamento', 'Peso corporal', 'seated hamstring stretch', 'tempo', 30],
  ['alongamento-quadriceps', 'Alongamento de quadríceps', ['alongar coxa'], 'Alongamento', 'Peso corporal', 'standing quadriceps stretch', 'tempo', 30],
  ['alongamento-gluteo', 'Alongamento de glúteo', ['pombo', 'figura 4'], 'Alongamento', 'Peso corporal', 'seated glute stretch', 'tempo', 30],
  ['alongamento-flexor-quadril', 'Alongamento de flexor do quadril', ['iliopsoas', 'afundo alongamento'], 'Alongamento', 'Peso corporal', 'hip flexor stretch', 'tempo', 30],
  ['alongamento-panturrilha', 'Alongamento de panturrilha', ['alongar panturrilha'], 'Alongamento', 'Peso corporal', 'calf stretch', 'tempo', 30],
  ['alongamento-peitoral', 'Alongamento de peitoral', ['alongar peito'], 'Alongamento', 'Peso corporal', 'chest stretch', 'tempo', 30],
  ['alongamento-ombro', 'Alongamento de ombro', ['alongar ombro', 'braço cruzado'], 'Alongamento', 'Peso corporal', 'shoulder stretch', 'tempo', 30],
  ['alongamento-triceps', 'Alongamento de tríceps', ['alongar tríceps'], 'Alongamento', 'Peso corporal', 'triceps stretch', 'tempo', 30],
  ['alongamento-lombar', 'Alongamento de lombar', ['postura da criança', 'joelhos no peito'], 'Alongamento', 'Peso corporal', 'lower back stretch', 'tempo', 30],
  ['gato-vaca', 'Gato e vaca', ['cat cow', 'mobilidade coluna'], 'Alongamento', 'Peso corporal', 'cat cow stretch', 'tempo', 45],
  ['mobilidade-toracica', 'Mobilidade torácica', ['rotação torácica', 'livro aberto'], 'Alongamento', 'Peso corporal', 'thoracic rotation', 'tempo', 45],
  ['mobilidade-quadril', 'Mobilidade de quadril 90/90', ['90 90', 'rotação de quadril'], 'Alongamento', 'Peso corporal', '90 90 hip stretch', 'tempo', 45],
];
